defaultTarget="TestCompilation"
defaultTestsPath=""
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    defaultTestsPath="~/Pharo/images/muOvm/generated/tests"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    defaultTestsPath="~/Documents/Pharo/images/muOvm/generated/tests"
fi

targetDirectory=""
testsPath=""
if test "$#" -eq 0; then
    #Default
    targetDirectory=$defaultTarget
    testsPath=$defaultTestsPath
elif test "$#" -eq 1; then
    #Default only the image
    targetDirectory=$1
    testsPath=$defaultTestsPath
elif test "$#" -eq 2; then
    #No defaults
    targetDirectory=$1
    testsPath=$2
elif test true; then
    echo 'usage: ./copystuff.sh [targetPath [imagePath]]'
    exit 1
fi

echo "targetDirectory = $targetDirectory"
echo "testsPath = $testsPath"
echo


echo "Copying support files into directory $targetDirectory"

#vmLibraryDirectory
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    cp ./build/build/vm/* $targetDirectory
elif [[ "$OSTYPE" == "darwin"* ]]; then
    cp ./build/build/vm/Debug/Pharo.app/Contents/MacOS/Plugins/* $targetDirectory
elif test true; then
    echo "Unsupported OS"
    exit 1
fi

cp ./build/generated/64/vm/src/* $targetDirectory
cp ./build/generated/64/vm/include/*.h $targetDirectory

cp ./tempConversion-64.image $targetDirectory
cp ./src/loadImage.c $targetDirectory
cp ../llstructures/llDictionary.c $targetDirectory
cp ../llstructures/llDictionary.h $targetDirectory


echo "Copying test case generated by image  files into directory $targetDirectory"

cp $testsPath/*.h $targetDirectory
cp $testsPath/*.c $targetDirectory
cp $testsPath/*.makefile $targetDirectory
