Class {
	#name : #TVisitor,
	#superclass : #Object,
	#category : #'VMMaker-Translation to C'
}

{ #category : #visiting }
TVisitor >> visitTAssignmentNode: aTAssignmentNode [
]

{ #category : #visiting }
TVisitor >> visitTBraceCaseNode: aTBraceCaseNode [

]

{ #category : #visiting }
TVisitor >> visitTCaseStmtNode: aTCaseStmtNode [

]

{ #category : #visiting }
TVisitor >> visitTConstantNode: aTConstantNode [

]

{ #category : #visiting }
TVisitor >> visitTDefineNode: aTDefineNode [

]

{ #category : #visiting }
TVisitor >> visitTGoToNode: aTPrintfTGoToNode [
]

{ #category : #visiting }
TVisitor >> visitTInlineNode: aTInlineNode [
]

{ #category : #visiting }
TVisitor >> visitTLabeledCommentNode: aTLabeledCommentNode [
]

{ #category : #visiting }
TVisitor >> visitTMethodNode: aTMethodNode [
]

{ #category : #visiting }
TVisitor >> visitTPrintfFormatStringNode: aTPrintfFormatStringNode [
]

{ #category : #visiting }
TVisitor >> visitTReturnNode: aTReturnNode [
]

{ #category : #visiting }
TVisitor >> visitTSendNode: aTSendNode [
]

{ #category : #visiting }
TVisitor >> visitTStmtListNode: aTStmtListNode [
]

{ #category : #visiting }
TVisitor >> visitTSwitchStmtNode: aTSwitchStmtNode [
]

{ #category : #visiting }
TVisitor >> visitTVariableNode: aTVariableNode [
]
